### ISSUE TITLE
Could not find a version that satisfies the requirement variantNet

### ISSUE THREAD

**Issue by pyghost504** [pb-jchin/VariantNET#2]
i tried using pip to  install VariantNet but it keeps giving me this error, can anyone help out on how i can install it?

**Comment by cschin** [comment]
@solokopi VariantNet is more like a demonstration than a "formal" library. There is no pip package for VariantNet. You will have install its other dependence through pip/conda, etc. And using a Jupyter notebook to try out some examples.

**Comment by pyghost504** [comment]
hello @cschin thank you for your swift response, i tried it on Jupyter notebook trying to replicate what you did but i got this still..

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-e84280e16a12> in <module>()
----> 1 import variantNet.utils as utils
      2 import variantNet.vn as vn

ModuleNotFoundError: No module named 'variantNet'
